POST http://localhost:3000/api/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODczNzRkY2JhYWE4NTNhZWQ3NGYyYiIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsImlhdCI6MTczNjkyMDA2NSwiZXhwIjoxNzM3MDA2NDY1fQ.A_XekvbWnR1B2jewrVUXaF2bX838ME4e2D4z53az9S4

{
    "buyer": "6787374dcbaaa853aed74f2b",
    "seller": "67873fb03c4ecb4e39ef007c",
    "totalAmount": 220.00,
    "hashedOTP": "324567wer"
}

#####

GET http://localhost:3000/api/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OWVkZjAwOWExN2NmMzFiODBhM2U3OSIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsImlhdCI6MTczODQ2NTAzNSwiZXhwIjoxNzM4NTUxNDM1fQ.mm-nlT2o9cW4AYeGUKvpCCaqH1QbPqXiquFuiWE0LUM

#####

GET http://localhost:3000/api/orders/user/679eb85793dea37ebf78ee6a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OWVkZjAwOWExN2NmMzFiODBhM2U3OSIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsImlhdCI6MTczODQ2NTAzNSwiZXhwIjoxNzM4NTUxNDM1fQ.mm-nlT2o9cW4AYeGUKvpCCaqH1QbPqXiquFuiWE0LUM

##################

DELETE http://localhost:3000/api/orders/679ecf052a81ddbd8fab6509
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OWVkZjAwOWExN2NmMzFiODBhM2U3OSIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsImlhdCI6MTczODQ2NTAzNSwiZXhwIjoxNzM4NTUxNDM1fQ.mm-nlT2o9cW4AYeGUKvpCCaqH1QbPqXiquFuiWE0LUM


##################
GET http://localhost:3000/api/items/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODczNzRkY2JhYWE4NTNhZWQ3NGYyYiIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsImlhdCI6MTczODM3ODM0MiwiZXhwIjoxNzM4NDY0NzQyfQ.HwSZrT8DCh3GtReXcSCcDhO2d41tSttUP1_8bzRRquI