POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john@example.com",
    "password": "securepassword123",
    "phone": "1234567890"
}

#################################
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "firstName": "Donald",
    "lastName": "Trump",
    "email": "seller@example.com",
    "password": "securepassword123",
    "phone": "9876543210"
}

#################################

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "john@example.com",
    "password": "securepassword123"
}

#################################


GET http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODczNzRkY2JhYWE4NTNhZWQ3NGYyYiIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsImlhdCI6MTczODM3ODM0MiwiZXhwIjoxNzM4NDY0NzQyfQ.HwSZrT8DCh3GtReXcSCcDhO2d41tSttUP1_8bzRRquI

#################################


DELETE http://localhost:3000/api/users/678d17d355b8037e36186b57
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODczNzRkY2JhYWE4NTNhZWQ3NGYyYiIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsImlhdCI6MTczODM3ODM0MiwiZXhwIjoxNzM4NDY0NzQyfQ.HwSZrT8DCh3GtReXcSCcDhO2d41tSttUP1_8bzRRquI
