POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john@example.com",
    "password": "securepassword123",
    "phone": "1234567890"
}

#################################
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "firstName": "Donald",
    "lastName": "Trump",
    "email": "seller@example.com",
    "password": "securepassword123",
    "phone": "9876543210"
}

#################################

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "john@example.com",
    "password": "securepassword123"
}

#################################


GET http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODczNzRkY2JhYWE4NTNhZWQ3NGYyYiIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsImlhdCI6MTczNzA4NTE4MSwiZXhwIjoxNzM3MTcxNTgxfQ.0XFAirwVy937B7kDJvRXiAMRk0j-IOd1nCH69uSS3ZY

#################################


DELETE http://localhost:3000/api/users/
Content-Type: application/json
